"""buyer_as_contact_order_inline_fields

Revision ID: 7a3cec30e271
Revises: a52ea27add81
Create Date: 2026-04-09 21:44:06.985310

"""
from alembic import op
import sqlalchemy as sa


revision = '7a3cec30e271'
down_revision = 'a52ea27add81'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('buyers', sa.Column('whatsapp', sa.String(), nullable=True))
    op.drop_column('buyers', 'rating')
    op.drop_column('buyers', 'is_approved')
    op.drop_column('buyers', 'password_hash')
    op.add_column('orders', sa.Column('buyer_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('buyer_phone', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('buyer_whatsapp', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('buyer_email', sa.String(), nullable=True))
    op.alter_column('orders', 'buyer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # Backfill buyer contact info from existing buyer records
    conn = op.get_bind()
    conn.execute(sa.text("""
        UPDATE orders o
        SET buyer_name    = b.full_name,
            buyer_phone   = b.phone,
            buyer_whatsapp = b.phone,
            buyer_email   = b.email
        FROM buyers b
        WHERE o.buyer_id = b.id
          AND o.buyer_name IS NULL
    """))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'buyer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('orders', 'buyer_email')
    op.drop_column('orders', 'buyer_whatsapp')
    op.drop_column('orders', 'buyer_phone')
    op.drop_column('orders', 'buyer_name')
    op.add_column('buyers', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('buyers', sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('buyers', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('buyers', 'whatsapp')
    # ### end Alembic commands ###
