"""add_is_approved_password_hash_to_buyers_sellers

Revision ID: a52ea27add81
Revises: e9b92151c296
Create Date: 2026-04-09 18:55:51.617980

"""
from alembic import op
import sqlalchemy as sa


revision = 'a52ea27add81'
down_revision = 'e9b92151c296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyers', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('buyers', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('sellers', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('sellers', sa.Column('password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'password_hash')
    op.drop_column('sellers', 'is_approved')
    op.drop_column('buyers', 'password_hash')
    op.drop_column('buyers', 'is_approved')
    # ### end Alembic commands ###
