"""add_rating_notes_to_sellers_buyers

Revision ID: e9b92151c296
Revises: b8d1fa1f2424
Create Date: 2026-04-08 20:42:00.227409

"""
from alembic import op
import sqlalchemy as sa


revision = 'e9b92151c296'
down_revision = 'b8d1fa1f2424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyers', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('buyers', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('sellers', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'rating')
    op.drop_column('buyers', 'rating')
    op.drop_column('buyers', 'notes')
    # ### end Alembic commands ###
